"""initial_core

Revision ID: e48ca3afc6c6
Revises: 
Create Date: 2026-07-19 12:35:56.115468
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e48ca3afc6c6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('color_palette',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('light_hex', sa.String(length=7), nullable=False),
    sa.Column('dark_hex', sa.String(length=7), nullable=False),
    sa.Column('text_hex', sa.String(length=7), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_color_palette')),
    sa.UniqueConstraint('key', name=op.f('uq_color_palette_key')),
    sa.UniqueConstraint('sort_order', name=op.f('uq_color_palette_sort_order'))
    )
    op.create_table('departments',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('code', name=op.f('uq_departments_code')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name')),
    sa.UniqueConstraint('sort_order', name=op.f('uq_departments_sort_order'))
    )
    op.create_table('list_templates',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('space_kind', sa.String(length=24), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_list_templates')),
    sa.UniqueConstraint('code', name=op.f('uq_list_templates_code'))
    )
    op.create_table('outbox_events',
    sa.Column('aggregate_type', sa.String(length=64), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_created_at'), 'outbox_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_table('users',
    sa.Column('max_user_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=12), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('max_user_id', name=op.f('uq_users_max_user_id'))
    )
    op.create_table('products',
    sa.Column('normalized_name', sa.String(length=180), nullable=False),
    sa.Column('display_name', sa.String(length=180), nullable=False),
    sa.Column('department_id', sa.SmallInteger(), nullable=False),
    sa.Column('default_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('default_unit', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_products_department_id_departments'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('normalized_name', name=op.f('uq_products_normalized_name'))
    )
    op.create_index(op.f('ix_products_department_id'), 'products', ['department_id'], unique=False)
    op.execute("CREATE INDEX ix_products_name_trgm ON products USING gin (normalized_name gin_trgm_ops)")
    op.create_table('spaces',
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('personal', 'family', 'shared')", name=op.f('ck_spaces_valid_kind')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_spaces_owner_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spaces'))
    )
    op.create_index(op.f('ix_spaces_owner_user_id'), 'spaces', ['owner_user_id'], unique=False)
    op.create_table('product_aliases',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('normalized_alias', sa.String(length=180), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_aliases_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_aliases'))
    )
    op.create_index(op.f('ix_product_aliases_normalized_alias'), 'product_aliases', ['normalized_alias'], unique=True)
    op.create_index(op.f('ix_product_aliases_product_id'), 'product_aliases', ['product_id'], unique=False)
    op.execute("CREATE INDEX ix_product_aliases_name_trgm ON product_aliases USING gin (normalized_alias gin_trgm_ops)")
    op.create_table('product_user_stats',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('add_count', sa.Integer(), nullable=False),
    sa.Column('purchase_count', sa.Integer(), nullable=False),
    sa.Column('last_added_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_user_stats_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_product_user_stats_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_user_stats')),
    sa.UniqueConstraint('user_id', 'product_id', name=op.f('uq_product_user_stats_user_id'))
    )
    op.create_index(op.f('ix_product_user_stats_product_id'), 'product_user_stats', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_user_stats_user_id'), 'product_user_stats', ['user_id'], unique=False)
    op.create_table('space_members',
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('color_id', sa.SmallInteger(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'editor', 'viewer')", name=op.f('ck_space_members_valid_role')),
    sa.ForeignKeyConstraint(['color_id'], ['color_palette.id'], name=op.f('fk_space_members_color_id_color_palette'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_space_members_space_id_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_space_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_space_members')),
    sa.UniqueConstraint('space_id', 'user_id', name=op.f('uq_space_members_space_id'))
    )
    op.create_index(op.f('ix_space_members_space_id'), 'space_members', ['space_id'], unique=False)
    op.create_index(op.f('ix_space_members_user_id'), 'space_members', ['user_id'], unique=False)
    op.create_index('uq_space_members_active_color', 'space_members', ['space_id', 'color_id'], unique=True, postgresql_where=sa.text('left_at IS NULL AND color_id IS NOT NULL'))
    op.create_table('template_items',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_template_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['list_templates.id'], name=op.f('fk_template_items_template_id_list_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_items')),
    sa.UniqueConstraint('template_id', 'product_id', name=op.f('uq_template_items_template_id'))
    )
    op.create_index(op.f('ix_template_items_template_id'), 'template_items', ['template_id'], unique=False)
    op.create_table('invitations',
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_member_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_uses > 0', name=op.f('ck_invitations_positive_max_uses')),
    sa.CheckConstraint('use_count >= 0', name=op.f('ck_invitations_nonnegative_use_count')),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['space_members.id'], name=op.f('fk_invitations_created_by_member_id_space_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_invitations_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_invitations_token_hash'))
    )
    op.create_index(op.f('ix_invitations_space_id'), 'invitations', ['space_id'], unique=False)
    op.create_table('shopping_lists',
    sa.Column('space_id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_member_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=24), server_default='personal', nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('personal', 'family', 'shared')", name=op.f('ck_shopping_lists_valid_category')),
    sa.CheckConstraint("status IN ('active', 'completed', 'archived')", name=op.f('ck_shopping_lists_valid_status')),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['space_members.id'], name=op.f('fk_shopping_lists_created_by_member_id_space_members'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_shopping_lists_space_id_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['list_templates.id'], name=op.f('fk_shopping_lists_template_id_list_templates'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_lists'))
    )
    op.create_index(op.f('ix_shopping_lists_space_id'), 'shopping_lists', ['space_id'], unique=False)
    op.create_table('section_assignments',
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('department_id', sa.SmallInteger(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_section_assignments_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], name=op.f('fk_section_assignments_list_id_shopping_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['space_members.id'], name=op.f('fk_section_assignments_member_id_space_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_section_assignments')),
    sa.UniqueConstraint('list_id', 'department_id', name=op.f('uq_section_assignments_list_id'))
    )
    op.create_index(op.f('ix_section_assignments_list_id'), 'section_assignments', ['list_id'], unique=False)
    op.create_index(op.f('ix_section_assignments_member_id'), 'section_assignments', ['member_id'], unique=False)
    op.create_table('shopping_items',
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('department_id', sa.SmallInteger(), nullable=False),
    sa.Column('created_by_member_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_member_id', sa.Uuid(), nullable=True),
    sa.Column('purchased_by_member_id', sa.Uuid(), nullable=True),
    sa.Column('display_name', sa.String(length=180), nullable=False),
    sa.Column('dedupe_key', sa.String(length=220), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'assigned', 'purchased', 'unavailable')", name=op.f('ck_shopping_items_valid_status')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_shopping_items_positive_quantity')),
    sa.ForeignKeyConstraint(['assigned_member_id'], ['space_members.id'], name=op.f('fk_shopping_items_assigned_member_id_space_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_member_id'], ['space_members.id'], name=op.f('fk_shopping_items_created_by_member_id_space_members'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_shopping_items_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], name=op.f('fk_shopping_items_list_id_shopping_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_shopping_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchased_by_member_id'], ['space_members.id'], name=op.f('fk_shopping_items_purchased_by_member_id_space_members'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_items'))
    )
    op.create_index(op.f('ix_shopping_items_assigned_member_id'), 'shopping_items', ['assigned_member_id'], unique=False)
    op.create_index(op.f('ix_shopping_items_department_id'), 'shopping_items', ['department_id'], unique=False)
    op.create_index(op.f('ix_shopping_items_list_id'), 'shopping_items', ['list_id'], unique=False)
    op.create_index(op.f('ix_shopping_items_product_id'), 'shopping_items', ['product_id'], unique=False)
    op.create_index('uq_shopping_items_active_dedupe', 'shopping_items', ['list_id', 'dedupe_key'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('shopping_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('list_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=True),
    sa.Column('actor_member_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_member_id'], ['space_members.id'], name=op.f('fk_shopping_events_actor_member_id_space_members'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['shopping_items.id'], name=op.f('fk_shopping_events_item_id_shopping_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], name=op.f('fk_shopping_events_list_id_shopping_lists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shopping_events'))
    )
    op.create_index(op.f('ix_shopping_events_created_at'), 'shopping_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_shopping_events_event_type'), 'shopping_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_shopping_events_item_id'), 'shopping_events', ['item_id'], unique=False)
    op.create_index(op.f('ix_shopping_events_list_id'), 'shopping_events', ['list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shopping_events_list_id'), table_name='shopping_events')
    op.drop_index(op.f('ix_shopping_events_item_id'), table_name='shopping_events')
    op.drop_index(op.f('ix_shopping_events_event_type'), table_name='shopping_events')
    op.drop_index(op.f('ix_shopping_events_created_at'), table_name='shopping_events')
    op.drop_table('shopping_events')
    op.drop_index('uq_shopping_items_active_dedupe', table_name='shopping_items', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_shopping_items_product_id'), table_name='shopping_items')
    op.drop_index(op.f('ix_shopping_items_list_id'), table_name='shopping_items')
    op.drop_index(op.f('ix_shopping_items_department_id'), table_name='shopping_items')
    op.drop_index(op.f('ix_shopping_items_assigned_member_id'), table_name='shopping_items')
    op.drop_table('shopping_items')
    op.drop_index(op.f('ix_section_assignments_member_id'), table_name='section_assignments')
    op.drop_index(op.f('ix_section_assignments_list_id'), table_name='section_assignments')
    op.drop_table('section_assignments')
    op.drop_index(op.f('ix_shopping_lists_space_id'), table_name='shopping_lists')
    op.drop_table('shopping_lists')
    op.drop_index(op.f('ix_invitations_space_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_template_items_template_id'), table_name='template_items')
    op.drop_table('template_items')
    op.drop_index('uq_space_members_active_color', table_name='space_members', postgresql_where=sa.text('left_at IS NULL AND color_id IS NOT NULL'))
    op.drop_index(op.f('ix_space_members_user_id'), table_name='space_members')
    op.drop_index(op.f('ix_space_members_space_id'), table_name='space_members')
    op.drop_table('space_members')
    op.drop_index(op.f('ix_product_user_stats_user_id'), table_name='product_user_stats')
    op.drop_index(op.f('ix_product_user_stats_product_id'), table_name='product_user_stats')
    op.drop_table('product_user_stats')
    op.drop_index(op.f('ix_product_aliases_product_id'), table_name='product_aliases')
    op.drop_index('ix_product_aliases_name_trgm', table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_normalized_alias'), table_name='product_aliases')
    op.drop_table('product_aliases')
    op.drop_index(op.f('ix_spaces_owner_user_id'), table_name='spaces')
    op.drop_table('spaces')
    op.drop_index(op.f('ix_products_department_id'), table_name='products')
    op.drop_index('ix_products_name_trgm', table_name='products')
    op.drop_table('products')
    op.drop_table('users')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_created_at'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_table('list_templates')
    op.drop_table('departments')
    op.drop_table('color_palette')
    # ### end Alembic commands ###
