"""Domain-level helpers shared across services."""

from .model_admin import (
    DEFAULT_RAG_PROFILE_SLUG,
    activate_chat_provider,
    ensure_chat_preference,
    get_active_rag_profile_slug,
    get_active_provider,
    get_ai_reply_debounce_seconds,
    get_chat_preference,
    get_effective_chat_preference,
    get_model_preference,
    get_rag_preference,
    get_rag_similarity,
    get_rag_temperature,
    set_active_provider,
    set_active_rag_profile_slug,
    set_ai_reply_debounce_seconds,
    set_chat_preference,
    set_model_preference,
    set_rag_similarity,
    set_rag_temperature,
    normalize_rag_profile_slug,
)

__all__ = [
    "activate_chat_provider",
    "DEFAULT_RAG_PROFILE_SLUG",
    "ensure_chat_preference",
    "get_active_rag_profile_slug",
    "get_active_provider",
    "get_ai_reply_debounce_seconds",
    "get_chat_preference",
    "get_effective_chat_preference",
    "get_model_preference",
    "get_rag_preference",
    "get_rag_similarity",
    "get_rag_temperature",
    "set_active_provider",
    "set_active_rag_profile_slug",
    "set_ai_reply_debounce_seconds",
    "set_chat_preference",
    "set_model_preference",
    "set_rag_similarity",
    "set_rag_temperature",
    "normalize_rag_profile_slug",
]
